baseURL: https://codemute.ml
relativeURLs: true
canonifyURLs: true
googleAnalytics: UA-28835595-1
disableKinds:
  - taxonomy
  - taxonomyTerm
permalinks:
  blog: "blog/:year/:month/:slug"
markup:
  defaultMarkdownHandler: blackfriday
  highlight:
    style: emacs
